spring:
  jpa:
    hibernate:
      ddl-auto: none
    database: h2
liquibase:
  change-log: classpath:db/master.xml
  enabled: true
  drop-first: true
  
logging:
  level:
    root: INFO
    com:
      brew: DEBUG
  